BUDGET = 100
SIMULATION_HORIZON = 8

INDICATORS = {
    "T1": "разгрузка дорог",
    "T2": "доступность общественного транспорта",
    "E1": "озеленение",
    "E2": "качество воздуха",
    "S1": "школы и детсады",
    "S2": "поликлиники",
    "B1": "безопасность улиц",
    "B2": "безопасность дорожного движения",
    "C1": "надёжность ЖКХ",
    "C2": "скорость решения обращений",
}

WEIGHTS = {
    "T1": 0.10,
    "T2": 0.10,
    "E1": 0.09,
    "E2": 0.11,
    "S1": 0.11,
    "S2": 0.11,
    "B1": 0.09,
    "B2": 0.09,
    "C1": 0.10,
    "C2": 0.10,
}

DISTRICTS = {
    "Есиль": {
        "population_share": 0.27,
        "indicators": {
            "T1": 45,
            "T2": 62,
            "E1": 68,
            "E2": 72,
            "S1": 48,
            "S2": 55,
            "B1": 78,
            "B2": 60,
            "C1": 75,
            "C2": 70,
        },
    },
    "Алматы": {
        "population_share": 0.24,
        "indicators": {
            "T1": 40,
            "T2": 75,
            "E1": 50,
            "E2": 55,
            "S1": 60,
            "S2": 65,
            "B1": 62,
            "B2": 52,
            "C1": 50,
            "C2": 60,
        },
    },
    "Сарыарка": {
        "population_share": 0.20,
        "indicators": {
            "T1": 50,
            "T2": 70,
            "E1": 42,
            "E2": 40,
            "S1": 62,
            "S2": 68,
            "B1": 58,
            "B2": 55,
            "C1": 45,
            "C2": 55,
        },
    },
    "Байконур": {
        "population_share": 0.13,
        "indicators": {
            "T1": 52,
            "T2": 68,
            "E1": 55,
            "E2": 50,
            "S1": 58,
            "S2": 60,
            "B1": 52,
            "B2": 58,
            "C1": 55,
            "C2": 58,
        },
    },
    "Нура": {
        "population_share": 0.16,
        "indicators": {
            "T1": 55,
            "T2": 40,
            "E1": 45,
            "E2": 65,
            "S1": 38,
            "S2": 35,
            "B1": 55,
            "B2": 50,
            "C1": 60,
            "C2": 50,
        },
    },
}

INITIATIVES = {
    "M1": {
        "id": "M1",
        "category": "transport",
        "name": "Выделенные полосы для автобусов",
        "type": "district",
        "cost": 18,
        "lag": 2,
        "effects": {"T1": 6, "T2": 9},
    },
    "M2": {
        "id": "M2",
        "category": "transport",
        "name": "Умные светофоры",
        "type": "city",
        "cost": 22,
        "lag": 2,
        "effects": {"T1": 4, "B2": 3},
    },
    "M3": {
        "id": "M3",
        "category": "transport",
        "name": "Линия ЛРТ / расширение",
        "type": "district",
        "cost": 30,
        "lag": 4,
        "effects": {"T1": 16, "T2": 20, "E2": 4},
    },
    "M4": {
        "id": "M4",
        "category": "ecology",
        "name": "Парк / сквер",
        "type": "district",
        "cost": 15,
        "lag": 2,
        "effects": {"E1": 12, "E2": 3, "B1": 2},
    },
    "M5": {
        "id": "M5",
        "category": "ecology",
        "name": "Перевод частного сектора на чистое топливо",
        "type": "district",
        "cost": 25,
        "lag": 3,
        "effects": {"E2": 14, "C1": 4},
    },
    "M6": {
        "id": "M6",
        "category": "ecology",
        "name": "Городская программа озеленения и ветрозащитных полос",
        "type": "city",
        "cost": 20,
        "lag": 4,
        "effects": {"E1": 5, "E2": 3},
    },
    "M7": {
        "id": "M7",
        "category": "social",
        "name": "Школа + детсад",
        "type": "district",
        "cost": 24,
        "lag": 3,
        "effects": {"S1": 16},
    },
    "M8": {
        "id": "M8",
        "category": "social",
        "name": "Центр семейного здоровья / поликлиника",
        "type": "district",
        "cost": 20,
        "lag": 3,
        "effects": {"S2": 14},
    },
    "M9": {
        "id": "M9",
        "category": "social",
        "name": "Дворовые спорт-хабы",
        "type": "district",
        "cost": 10,
        "lag": 1,
        "effects": {"S1": 3, "S2": 3, "B1": 3},
    },
    "M10": {
        "id": "M10",
        "category": "safety",
        "name": "Освещение и камеры",
        "type": "district",
        "cost": 12,
        "lag": 1,
        "effects": {"B1": 12, "B2": 2},
    },
    "M11": {
        "id": "M11",
        "category": "safety",
        "name": "Безопасные переходы и школьные зоны",
        "type": "district",
        "cost": 10,
        "lag": 1,
        "effects": {"B2": 12, "T1": -2},
    },
    "M12": {
        "id": "M12",
        "category": "services",
        "name": "Единая цифровая платформа обращений",
        "type": "city",
        "cost": 14,
        "lag": 1,
        "effects": {"C2": 5},
    },
    "M13": {
        "id": "M13",
        "category": "services",
        "name": "Модернизация тепло- и водосетей",
        "type": "district",
        "cost": 28,
        "lag": 4,
        "effects": {"C1": 18, "E2": 2},
    },
    "M14": {
        "id": "M14",
        "category": "services",
        "name": "Аварийные бригады ЖКХ + раннее оповещение",
        "type": "city",
        "cost": 16,
        "lag": 1,
        "effects": {"C1": 5, "C2": 2},
    },
}

SYNERGIES = [
    {"requires": ("M1", "M2"), "source": "M1", "effects": {"T1": 2}},
    {"requires": ("M10", "M12"), "source": "M10", "effects": {"B1": 2}},
    {"requires": ("M5", "M6"), "source": "M5", "effects": {"E2": 2}},
]

INCOMPATIBILITIES = [
    {"initiatives": ("M1", "M3"), "scope": "global"},
    {"initiatives": ("M4", "M7"), "scope": "district"},
    {"initiatives": ("M5", "M13"), "scope": "district"},
]
